name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: python health checks
  # You may pin to the exact commit or the version.
  # uses: Equator-AI/python-health-checks@f705f542e52c953e49f56ffa85478ecbd2bf4600
        uses: Equator-AI/python-health-checks@v2.1.2
        
      - name: Run tests
        run: pytest
      
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-app \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
